# Generated by Django 5.0.6 on 2024-06-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_adjustments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockadjustment',
            name='adjustment_type',
        ),
    ]
